source 'https://github.com/CocoaPods/Specs.git' # cocoapods仓库
source 'https://github.com/TuyaInc/TYPublicSpecs.git'   # 涂鸦的公开仓库
# source 'GROUP_SPEC'


# 请把你的开发调试阶段使用的三方写在这里，业务必须依赖请写在*.podspec
target 'PROJECT_Example' do

    pod 'PROJECT', :path => '../' # 当前正在开发的模块，以本地路径方式引入工程，方便与其它库统一管理

  pod 'TYModuleServices'    # 涂鸦的业务开放的服务
  
#  pod 'TYModuleManagerExample'  # 一个示例demo

  target 'PROJECT_Tests' do
    inherit! :search_paths

  end

end
